version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Хост портът е 5433, вътрешният е 5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Пренасочва порт 5000 от контейнера към хоста
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - db

volumes:
  db_data:
